// My header

// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type CreateProjectModel = { path: string; name: string; description?: string | null }

export type ProjectConfiguration = { name: string; description?: string | null; current_tabs?: string[]; created_on: string; last_access: string }

export type SerializableError = { err: "unhandled"; context: string } | { err: "io"; context: string } | { err: "non_empty_project_folder"; context: string } | { err: "expected_project_directory"; context: string } | { err: "json_encoding"; context: string } | { err: "database_error"; context: string } | { err: "no_active_project" } | { err: "invalid_project_selection"; context: string } | { err: "corrupted_project"; context: string }

const ARGS_MAP = { 'application':'{"create_project":["project"],"open_project":["path"]}' }
export type Router = { "application": {create_project: (project: CreateProjectModel) => Promise<ProjectConfiguration>, 
open_project: (path: string) => Promise<ProjectConfiguration>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
