// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type MetaError = { code: string; message: string }

const ARGS_MAP = { 'projects':'{"create_project":["name","path"]}' }
export type Router = { "projects": {create_project: (name: string, path: string) => Promise<string>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
